FROM golang:1.12.5-alpine as builder

RUN apk update && apk add --no-cache git

ENV USER=appuser
ENV UID=10001

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

WORKDIR $GOPATH/src/app/

COPY . .

RUN go mod download
RUN go mod verify

RUN CGO_ENABLED=0 GOOS=linux go build \
    -a -installsuffix cgo -o /app/main . && \
    chmod 755 /app

FROM scratch

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /app /app
COPY form.html /static/

EXPOSE 8080

ENTRYPOINT ["./app"]